Repository tiemonl/imhungry, pull requests merged in 2019-03, with the labels that each got.

#13 Add DI module for notifications
  app/src/main/kotlin/io/imhungry/common/di/AppComponent.kt
  app/src/main/kotlin/io/imhungry/common/di/AppModule.kt
  app/src/main/kotlin/io/imhungry/home/ui/HomeActivity.kt
  app/src/main/kotlin/io/imhungry/notifications/di/NotificationModule.kt
Labels: enhancement

#12 Refactor of code to use features as top-level packages instead of components
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/imhungry/MainApplication.kt
  app/src/main/kotlin/io/imhungry/common/di/AppComponent.kt
  app/src/main/kotlin/io/imhungry/common/di/AppModule.kt
  app/src/main/kotlin/io/imhungry/common/di/ViewModelModule.kt
  app/src/main/kotlin/io/imhungry/common/ui/BaseActivity.kt
  app/src/main/kotlin/io/imhungry/common/vm/BaseViewModel.kt
  app/src/main/kotlin/io/imhungry/di/ActivityModule.kt
  app/src/main/kotlin/io/imhungry/home/di/HomeModule.kt
  app/src/main/kotlin/io/imhungry/home/ui/HomeActivity.kt
  app/src/main/kotlin/io/imhungry/home/vm/HomeViewModel.kt
  app/src/main/kotlin/io/imhungry/launcher/ui/LauncherActivity.kt
  app/src/main/kotlin/io/imhungry/login/ui/LoginActivity.kt
  app/src/main/kotlin/io/imhungry/maps/di/MapsModule.kt
  app/src/main/kotlin/io/imhungry/maps/ui/MapActivity.kt
  app/src/main/kotlin/io/imhungry/maps/vm/MapViewModel.kt
  app/src/main/kotlin/io/imhungry/notifications/di/NotificationModule.kt
  app/src/main/kotlin/io/imhungry/room/db/ImhungryDao.kt
  app/src/main/kotlin/io/imhungry/room/db/ImhungryDatabase.kt
  app/src/main/kotlin/io/imhungry/room/db/ImhungryRepository.kt
  app/src/main/kotlin/io/imhungry/room/di/RoomModule.kt
  app/src/main/kotlin/io/imhungry/room/model/RestaurantEntity.kt
  app/src/main/kotlin/io/imhungry/room/model/RestaurantTagEntity.kt
  app/src/main/kotlin/io/imhungry/room/model/TagEntity.kt
  app/src/main/kotlin/io/imhungry/settings/SettingsActivity.kt
  app/src/main/kotlin/io/imhungry/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_settings.xml
Labels: enhancement

#15 Refactor Login UI/Flow, migrate to Firebase Auth UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/imhungry/common/ui/BaseActivity.kt
  app/src/main/kotlin/io/imhungry/home/ui/HomeActivity.kt
  app/src/main/kotlin/io/imhungry/launcher/ui/LauncherActivity.kt
  app/src/main/kotlin/io/imhungry/login/LoginUtil.kt
  app/src/main/kotlin/io/imhungry/login/ui/LoginActivity.kt
  app/src/main/res/drawable/ic_imhungry_logo.xml
  app/src/main/res/drawable/ic_imhungry_logo_outlined.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#52 GH-50: Fix occasional app crash when starting map activity
  app/src/main/kotlin/io/imhungry/maps/ui/MapActivity.kt
Labels: Type: Bug

#54 GH-51: Configure CircleCI for Android
  .circleci/config.yml
Labels: Type: Enhancement

#49 GH-28: Add Bottom Navigation
  app/build.gradle
  app/src/main/kotlin/io/imhungry/fragments/BottomNavigationFragment.kt
  app/src/main/kotlin/io/imhungry/home/ui/HomeActivity.kt
  app/src/main/res/drawable-anydpi/ic_navigation_home.xml
  app/src/main/res/drawable-anydpi/ic_navigation_map.xml
  app/src/main/res/drawable-anydpi/ic_navigation_more.xml
  app/src/main/res/drawable-hdpi/ic_navigation_home.png
  app/src/main/res/drawable-hdpi/ic_navigation_map.png
  app/src/main/res/drawable-hdpi/ic_navigation_more.png
  app/src/main/res/drawable-mdpi/ic_navigation_home.png
  app/src/main/res/drawable-mdpi/ic_navigation_map.png
  app/src/main/res/drawable-mdpi/ic_navigation_more.png
  app/src/main/res/drawable-xhdpi/ic_navigation_home.png
  app/src/main/res/drawable-xhdpi/ic_navigation_map.png
  app/src/main/res/drawable-xhdpi/ic_navigation_more.png
  app/src/main/res/drawable-xxhdpi/ic_navigation_home.png
  app/src/main/res/drawable-xxhdpi/ic_navigation_map.png
  app/src/main/res/drawable-xxhdpi/ic_navigation_more.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/bottom_nav.xml
  app/src/main/res/layout/fragment_bottom_navigation.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Type: Enhancement

#56 NOGH: Move navigation to its own package
  app/src/main/kotlin/io/imhungry/navigation/BottomNavigationFragment.kt
  app/src/main/res/layout/bottom_nav.xml
  app/src/main/res/layout/fragment_bottom_navigation.xml
Labels: Type: Maintenance

#59 GH-31: added google auth
  app/src/main/kotlin/io/imhungry/login/LoginUtil.kt
Labels: Priority: Low, Status: In Review, Type: Enhancement

#60 GH-55: Prevent re-launching of current activity in bottom nav
  app/src/main/kotlin/io/imhungry/navigation/BottomNavigationFragment.kt
Labels: Type: Bug

#62 GH-61: Add Code Coverage to CI Pipeline
  .circleci/config.yml
  .codecov/codecov.yml
  README.md
  app/build.gradle
  build.gradle
Labels: Type: Maintenance

#65 Feature/gh 64 add codecov webhook
  .codecov/codecov.yml
Labels: Priority: Low, Status: Complete, Type: Maintenance

#66 NOGH: Update codecov.yml
  .codecov/codecov.yml
Labels: Type: Maintenance

#70 GH-69: added ignore section to codecov
  .codecov/codecov.yml
Labels: Priority: Low, Type: Enhancement

#72 GH-71: Refactor settings, add fragment and preferences XML
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/imhungry/common/ui/BaseActivity.kt
  app/src/main/kotlin/io/imhungry/common/ui/NavigationActivity.kt
  app/src/main/kotlin/io/imhungry/home/ui/HomeActivity.kt
  app/src/main/kotlin/io/imhungry/login/LoginInteractorActivity.kt
  app/src/main/kotlin/io/imhungry/login/LoginUtil.kt
  app/src/main/kotlin/io/imhungry/maps/ui/MapActivity.kt
  app/src/main/kotlin/io/imhungry/settings/SettingsActivity.kt
  app/src/main/kotlin/io/imhungry/settings/SettingsFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: Priority: Medium, Type: Enhancement

#73 GH-47: Begin refactor of maps
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/imhungry/maps/ui/MapActivity.kt
  app/src/main/kotlin/io/imhungry/maps/ui/adapters/MapItemAdapter.kt
  app/src/main/kotlin/io/imhungry/maps/ui/adapters/PlacesImageAdapter.kt
  app/src/main/kotlin/io/imhungry/maps/vm/MapViewModel.kt
  app/src/main/res/layout/list_item_image.xml
  app/src/main/res/layout/list_item_restaurant.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Priority: Medium, Type: Enhancement

#75 GH-63: Fix CodeCov, add Unit Tests
  .circleci/config.yml
  app/build.gradle
  app/src/main/kotlin/io/imhungry/login/LoginUtil.kt
  app/src/test/kotlin/io/imhungry/login/LoginUtilTest.kt
  build.gradle
Labels: Priority: Medium, Type: Enhancement

#76 NOGH: added authfailback back to the project
  .codecov/codecov.yml
  app/src/main/kotlin/io/imhungry/common/ui/BaseActivity.kt
  app/src/main/kotlin/io/imhungry/launcher/ui/LauncherActivity.kt
  app/src/main/kotlin/io/imhungry/login/AuthFailureCallback.kt
  app/src/main/kotlin/io/imhungry/login/LoginUtil.kt
  app/src/test/kotlin/io/imhungry/login/LoginUtilTest.kt
  build.gradle
Labels: Priority: Medium, Type: Enhancement

#77 NOGH: add coveralls
  .circleci/config.yml
  README.md
  app/build.gradle
  build.gradle
Labels: Priority: Low, Type: Enhancement

#79 NOGH: small workflow changes
  .circleci/config.yml
  .codecov/codecov.yml
Labels: Priority: Low, Type: Maintenance

#81 GH-58: Re-create app icons with higher resolution source
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: Priority: Low, Type: Maintenance

#84 Add bottom nav activities
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/imhungry/calendar/ui/CalendarActivity.kt
  app/src/main/kotlin/io/imhungry/navigation/BottomNavigationFragment.kt
  app/src/main/kotlin/io/imhungry/restaurantLists/ui/RestaurantListsActivtiy.kt
  app/src/main/res/drawable-anydpi/ic_navigation_calendar.xml
  app/src/main/res/drawable-anydpi/ic_navigation_restaurant_lists.xml
  app/src/main/res/drawable-hdpi/ic_navigation_calendar.png
  app/src/main/res/drawable-hdpi/ic_navigation_restaurant_lists.png
  app/src/main/res/drawable-mdpi/ic_navigation_calendar.png
  app/src/main/res/drawable-mdpi/ic_navigation_restaurant_lists.png
  app/src/main/res/drawable-xhdpi/ic_navigation_calendar.png
  app/src/main/res/drawable-xhdpi/ic_navigation_restaurant_lists.png
  app/src/main/res/drawable-xxhdpi/ic_navigation_calendar.png
  app/src/main/res/drawable-xxhdpi/ic_navigation_restaurant_lists.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_restaurant_lists_activtiy.xml
  app/src/main/res/layout/fragment_bottom_navigation.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Priority: Medium, Type: Enhancement

#86 GH-85: Add crashlytics SDK
  app/build.gradle
  build.gradle
Labels: Priority: Medium, Type: Maintenance

#87 GH-83: Add Firebase models and repositories
  app/build.gradle
  app/src/main/kotlin/io/imhungry/common/di/AppComponent.kt
  app/src/main/kotlin/io/imhungry/firebase/di/FirebaseProviderModule.kt
  app/src/main/kotlin/io/imhungry/firebase/model/places/FirebasePlace.kt
  app/src/main/kotlin/io/imhungry/firebase/model/places/FirebaseReview.kt
  app/src/main/kotlin/io/imhungry/firebase/model/places/FirebaseVisit.kt
  app/src/main/kotlin/io/imhungry/firebase/model/user/FirebaseUser.kt
  app/src/main/kotlin/io/imhungry/firebase/model/user/privacy/FirebasePrivacyConfig.kt
  app/src/main/kotlin/io/imhungry/firebase/model/user/privacy/FirebasePrivacyLevel.kt
  app/src/main/kotlin/io/imhungry/firebase/repository/FirebaseBaseCollectionRepository.kt
  app/src/main/kotlin/io/imhungry/firebase/repository/FirebasePlaceRepository.kt
  app/src/main/kotlin/io/imhungry/firebase/repository/FirebaseReviewRepository.kt
  app/src/main/kotlin/io/imhungry/firebase/repository/FirebaseUserRepository.kt
  app/src/main/kotlin/io/imhungry/firebase/repository/FirebaseVisitRepository.kt
  lint.xml
Labels: Priority: Medium, Type: Enhancement
